backend:
    name: git-gateway
    branch: master

media_folder: "src/assets/images/uploads"
public_folder: "/images/uploads"

collections:
    - name: "soldiers"
      label: "Fallen Soldiers"
      label_singular: "Soldier"
      editor:
        preview: false
      folder: "src/content/soldiers"
      format: "json"
      delete: true
      create: true
      fields:
        - {label: "Name", name: "name", widget: "string"}
        - {label: "Biography", name: "bio", widget: "markdown"}
        - {label: "Photo", name: "photo", widget: "image"}
    - name: "pages"
      label: "Pages"
      delete: false
      editor:
        preview: false
      files:
        - name: "home"
          label: "Home Page"
          file: "src/content/home.md"
          delete: false
          fields:
            - {label: "Search Field Label", name: "label", widget: "string"}
            - {label: "Search Field Placeholder", name: "placeholder", widget: "string"}