backend:
    name: git-gateway
    branch: master

media_library:
  name: cloudinary
  config:
    cloud_name: dfdfods4n
    api_key: 219668172845878
    multiple: true

collections:
    - name: "settings"
      label: "Settings"
      delete: false
      editor:
        preview: false
      files:
        - name: "soldiers"
          label: "Fallen Soldiers"
          file: "src/content/soldiers.md"
          delete: false
          fields:
            - name: "soldiers"
              label: "Fallen Soldiers"
              label_singular: "Soldier"
              widget: "list"
              fields:
                - {label: "Name", name: "name", widget: "string"}
                - {label: "Biography", name: "bio", widget: "markdown"}
                - {label: "Photo", name: "photo", widget: "image"}